name = "cloudflare-upload"
main = "src/index.js"
# use current date 
compatibility_date = "2024-05-07" 
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
r2_buckets = [{ binding = "MY_BUCKET", bucket_name = "portfolio-uploads" }]
