name: Generate a build and push to another branch

permissions:
  contents: write

on:
  push:
    branches:
      - mvp

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    env:
      VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
      VITE_PORT: ${{ secrets.VITE_PORT }}
      VITE_CLOUDFLARE_WORKER_URL: ${{ secrets.VITE_CLOUDFLARE_WORKER_URL }}
      VITE_MY_BUCKET: ${{ secrets.VITE_MY_BUCKET }}
      VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
      VITE_CLIENT_URL: ${{ secrets.VITE_CLIENT_URL }}
      VITE_SERVICE_ACCOUNT_KEY: ${{ secrets.VITE_SERVICE_ACCOUNT_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        working-directory: client
        run: npm install

      - name: Generate Sitemap
        working-directory: client
        run: npm run sitemap

      - name: Build
        working-directory: client
        run: npm run build

      - name: Debug build output
        working-directory: client
        run: ls -la && ls -la ./dist

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch where built assets go
          FOLDER: client/dist # IMPORTANT: point to frontend dist folder
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
